; HEADER_BLOCK_START
; generated by Creality_Print V7.1.1.4472 on 2026-05-16 at 10:34:18
; total layer number: 3
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 0.60
; creality_uuid: 7a5a4631-af6b-43f6-aeb1-9c8cd107bd19
; HEADER_BLOCK_END

; MINX = 4.67
; MINY = 5.00
; MINZ = 0.00
; MAXX = 62.87
; MAXY = 55.40
; MAXZ = 0.50

; multicolor_method = 0 
; THUMBNAIL_BLOCK_START

;
; png begin 96*96 1248 8 71 3
; iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAADb0lEQVR4Ae3c6WoTURQH8AsidsueJt
; PsjdoVNaiIuHVUtO7GBaoIMogfXFAj+FXyCHmEPEIeIY/QV3L+hYExNNBk7p05k/x/H6XSztx77j3n
; LqMUERERERERERERERERERERERFRSM5+WOtvfakMdn/Xh813Vi93OdlONBdbpxOn0orMSawvtvDyj/
; l3u7yf65buZztolMabYq/6bLXDRtGo/qrQXbub7Z705/2NcuFP4xAR03hb7GYvJWw2ygRSG0ut5nur
; t1xbsJUGa/eyXTTMeafU3/xcPmqU5MaSjd+j6H+VJ/mOO5ScuNdPy2uUyn6OQxjgoTFk6Or10xgdwh
; Axc9Eo2YsJe+NTeaAEQqMgWtAoiJJ6u2A8OkOFhwrS6/NXkra1l+k0D6z+zs/acPdXbYhIwosy0XOt
; 2xlnqXSmoeIOE2CQl4/0FP+/cCM9tkei5x6Xwga1fmDFOwow0WKsVVM697HUmyQ91a14K91WcYThAE
; NEkCFn+3u1vxLhRA0r9YUWagsVJ0V37Nz+Vh2qAFavpdpRv3xPrIYhjMNB00tET/lBrqOEcP8WR3xq
; iokSubTSoPIo7yhhCtdTcucChGiQiXYU0k0ljJsIOEoa3es4nuJNeZlH1c3mRNUESC+DTrTjSGwAED
; MZW3cyjsl1nNqLVTETsJ+YmsB0OEqd8ETVBCbDEQ8qNQoqj4VkaKbDsfww15G4DCCmJggjHLe+Vge1
; 5/IiQcwQid6gDEttLtvufvHRDpaUalRMTRBmOGKzxH8qwi38IosMRICYmkB0iW6QmCRBZIkeAjHPLS
; ocQ4QkREyWJjVnN63xuiDjufNXk3M5D2AYmpuaQCox0S8mHEOU3nZrlJeFnpIgFtt2GgU942REGJVx
; 1LAJpWvrVbtZz4Z0b71ql9ldmclj4KhzTGy9GoHNGjVDdJxxCtUsLU3oOOMUOlEl+pTG3VWLjThHQd
; SHgbWI47l6U2ecIuOGcGx6UdAj9CKld5Zt7/ooLsdJvHsl4a5aaHCDpfo030UJ793pxfXRqIYqyXfV
; QuNdH/V/lsDayzimo0XkOo4U/uujrb/NQ513er11HL78CfkbxT+ETfJZgpmcaKPmDWE7P2oD/2cJEC
; 3ez6CB8B0K9vqQjH6WIFbrOEREREREREREREREREREREREFHv/AGC/5F5iO0wxAAAAAElFTkSuQmCC
; png end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; png begin 300*300 4504 25 224 3
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAM90lEQVR4Ae3dXXNd5XUA4D0wbTBgak
; iDceyolmR9f8tY2LKwJNtAZzodcpUL2ouUNG3uyEynTZqEqi0wdac4niQEJ+DUgMkHgdghk8wkk4vz
; E/QT9BP0E3bOOmabY40sHUlH0n73eZ6ZfYG4ANnnrP2utddaO8sAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAACgs/3ZwfsPTf1n7/Uzbwwun3z1xK2Bfzq29JcnH1mIn2cAZRGB6eKvJ1enXzmRT//3ib
; wesPJT/9uXz745lM+/P5YvfjC+OrXUe6v/xaONIPYX/Q9OZgB7bfRf/urKufdG8/FvducPdT2wED87
; 2H1g4cj5x5biiuBVXM1B7Nw7o6szr/fXRl7qutL7whNfjyDmNAbsiggws1eHlp+81Jf3vHCkVgSrjR
; RBrP8rR2vNQez09wfzubeH87lrw6uRUk5+p+e6IAa0RQSTxV+MN05Vh+cOLWU7sF4Qi2vmcn8jiMV/
; J4JYpJRFXezBz3/meAawkTjtnHljqHb6B4N3pYDt1kpKufDTsTsp5ZGFR7/oNAbc0fW3n/vyc7+fzi
; df7mmkgNke2yiIRUqpLgY0RLvC3E9GdvVUtV2t1sVOXerTagFVFieU+RtjK9GusB+nqu0qgtiGTynf
; HV3RagEVEaeRdhXWy2CrrRaRAkspoeTiS1o/fSzPXB5ouV0hVc1BbKOU8uyPh7VaQNnEF/LCryYap6
; qUUsB226zVoqiLNbdaCGKwR4o5wNkfDZeysF4GW221KOpiAhm0UaqF9TLQagF7aL05QHZuq60Wghhs
; YDtzgOzMvepiEciKEaSi1aKoi2m1oOO1cw6QndFqAfcQH/L6ieqWwnq5bdZq8fT1kUYQi1YLdTEqqX
; nBnsJ6mu6VUq6ti9n2StKisF7WOUB2ppURJNteSULRrlAU1jM6wmZ1sb/+48ncPjFKRWGdtYogNvly
; Ty1Sxgz2W/OCvaq2K8TpIFKbWNpXXPHPOstbc/S5zy6d/3BiJYP9tN8L9nZDBKM4DTx1ZaB25odDK1
; GTmXtruF5oHmhcT333k+vKQF5/apY//f8jeT0NXre7POOOmBeNP9sM9kOZF+xtVXyRJr7dfX3hZ2N5
; Peg0fqe4Jr/d07ieOPfo0hPzn1wLt68ji4/duU7Wn4QWV/OIzIWbE6vRWe7pWZaN/9vx2szl/lsZ7K
; UqzQHGSejix5P5qf/rz8f+9XjjOnz20NJOanB3WgH+8Wjt5GufFJ6vDkVHeSN43f/AfR0ZuB7pfbDR
; 5iJ9Zs9EqlTMAaZcWI+2i8Wfj+XT/9XbCFKPzx5aeugLu/tyiwhe06/05gcO/3nHpopxgo2bRAa7KU
; 5Vc9dGkp8DjC/LM7+Zarwpup6iNE5T2R56+PiBhayDfeFvPrc0++aQdhd2T/OCvVRPVXeNCH2je88D
; FbdFWvjs76ZzDyRou/iSR5E09TnA+HLUH6mvVulJZsqm/qNXTxbtVZU5wKKZdeLfjQiVRdGTpfhOW1
; RlDjDu4tEj1ft3R2oPC1aloieLHVs7B5hysIqTVRGsMkqn6/nHl/RksW1VmgOMdDZ+F8GqvKL4fuGj
; iVUD0WxJ1eYA45QYo0KCVflFP5/iOy2r2hxgBN/FD8ZXBKs0RE/W/I3R5Qw2U6U5wELURGIMRoE9HV
; F8jxQ+g/VU9X2A8XvFh98errTEQHQ8lc5gragXVHXB3rl3R5f7vvx5qWBioifr2d9OGYjmU3H6iC/0
; zOWBSi7Yi1pctDBIBdOkJ4s7mucAqzqWcuHm5IpUMF1RfK/XHvVkdbI4YkdhvervAyxqVxnJip6s5/
; 7gJRUdq6qF9fVEwXbgq8fUrhKnJ6tDxRe4WLDXCcO+kQ6qXaUv0sKnr4/oyeoUcaqavTqU/IK9rYi0
; N178kFEJerI6RKe+DzCeDvb9w1FpREXoyaq4u7ZoduAr4ePDffTZzwpYFeElFRVWLNjr5C2aZ98aVm
; yvmMVfjuvJqpqqLNjbqWiGzagUPVkVsnbBXtbh5m+MevV5xejJqogqzwFu14WbEwJWBXlJRcLiThOp
; T1UW7LXT/HtSwiqKgWg9WQmKx/bx0s8qzwHuxDO/ndKDVVF6shLTCXOAO7Xw8/EVtY5qip4sL6lIxP
; lfjnfEHOBOTb7cc8sj8GrSk5WQOA4Pfu2Yu8smur/0xJLO6Opa+NlYHmWRjHIzotAaxdlqi56s2TeH
; ZBllZ21s6y7cVJytKj1ZCbE2tjXj3zheiwcUGZWkJysRRhRa88iJBxfqwd0bhCsqso3zH2oQLj3H4d
; bNXh3KBffqkm0kwtrY1jROWTd9qKuq6/nHl/RkJcDa2NaNvNRVu/jxpNSwgiLbuPCRtD8JRhRaE6es
; SA0jwHu6Wj2yjUToyWpdBK2zbw/n0bsjaFVLZBvzNwy7l54Rha15dOzhL559a9hJq4IufjyVx064jH
; KzNnZrIshH0Iplh9Lp6pBtJEJP1tYdrAet098bzOffH1vt/tLhrzttpc8ESCL0ZG1PBK2Z1/vzuXpd
; a+byQM1pK316shJhRGH7Br92rPbUdwfy+ffG8vqpq6YOkq7oyZJtJMBmgp052HNgYfCfj9VmXh/Iz7
; 07Wj9x9dfiBbTSi7ToyUqInqydi8A18NVjtSf/py+Pvq168Fo9damvsQhQ8EqDnqxEWBvbPhG4jpx/
; bOnkaydiDrERvOauDa/Wa161/hePLsWNQQArJxMgidCTtTsOdn8avJoDWP0JY37undFGEBt5qetK3N
; UjjYxgdv9n7vN3sI9kG4mwNnb3RfBqBLBX6wGs6YoX2D71vcH8zA+H8ox9pScrEXqy9kcjiC1+emXs
; q3gIJdtIgJ4suM0ESCL0ZIFsIxnWxoJsIylGFEC2kQxrY8EESDKKEQVPSeh0erISYUQBbvdkeTdlAq
; yNBRMgSbE2Fm73ZJkAScDEt7o9JaHj6clKhLWxoCcrKXqyQE9WMqyNBRMgybA2Fm6TbSRCTxbYypsM
; a2NBT1ZSjCiAbCMZ1saCCZBkWBsLWRYvCln8xXjuRSEJsDaWThU36icv9d06/YPBfPyb3QJWCowo0I
; niJn3+w4nVyZd78p4XjtQy0mBEgU4Tq2XmfjLSOFU91PXAQkZajCjQCWJLyfyNsZV4X6RTVcKsjaXq
; 4oYchfU4VR2eO+TmnDo9WVRRnKrOvTu6PHN5oHGqkgJWhLWxVE20K8SNOE5VUsCKMaJAVcRnOG6+sz
; 8aVlivMmtjSV1RWJ9+5YRTVdXpySJlMWYWc4FOVR1CTxYpilPV7NWh5aJdQbDqIHqySEkxB6hdoUNZ
; G0sKijlAhXWsjaXUol8wnmgrrNNgbSxlFYV1c4DcRU8WZbN2DlCw4i7WxlIWCutsytpY9luc8M+8MV
; SLBXtOVWzq2d9N53EUz2CPxcTFc7+fzi3Yo2UT3+rWk8Wes2CPbYmerHrtYEXxnb1gDpAd05PFXoiT
; fDEHqLDOtnU9//iSnix2S7FgT7sCbRE9WRc+mlg1EE27NS/Yc6qibfRk0U5RE41TuzlAdkX0ZHlJBe
; 1gDpA94SUV7JQFe+yZGIiOD1wGW2TBHnsuerIMRLNV5gDZN/GSCj1ZtMIcIPvOSypohTlASsFLKtiM
; OUBKxUsqWI85QEop0sKLtyZXJ7/Tcz0KqvFBVYjvbHEDU1intE6+diI/+eqJfOZyfz739nAeH9Yzbw
; wuTy313ooPb/RrCWLVV8wBzlweUFinvO4/cN+hg90HFo6cf2wprghexVUvyuezbw7l8++P5Qs/HVud
; eb2/NvJS15V4uug0Vh3Nc4BSQJK0URA7/f3BRhA7987onSAmpUxP/F1FYd0cIJVVBLH+rxytrQ1ikV
; LOXRtejZTy1KW+RkopiJWTwjodqwhi653GirpYvT6y0lwXs19+/5gDhDVaqYs1p5TRoOg0trvMAcIW
; NAex9VLKp6+PNILY2R8PL6uLtZc5QGiT9YJYXGvrYvWfabXYovhzqp+oLNiD3bRRXaxIKRc/GF+Nul
; j/i0fVxdZhwR7sI60WrYvCujlAKKFWWy06YQSpaFcoCusZUH73qos1t1qsHUFKfXOFwjpUSFVbLeL/
; L+YALdiDiku91SKC6jO/mbJgDzpZCq0W5gCBeypLq4U5QGBbtloX22lKGae5Yg5QYR3Ysc3qYkVKGX
; WxVlst4t/PXRsxBwjsjXvVxTba9hqtFs0L9pyqgH3TSkpZP4kprAPltDaI9f69wjoAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAADU/Qm66nxFofduKAAAAABJRU5ErkJggg==
; png end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.42mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=Part1.STL_id_0_copy_0 CENTER=33.768,30.2042 POLYGON=[[4.66953,30.2042],[19.2188,5.00417],[48.3172,5.00417],[62.8664,30.2042],[48.3172,55.4042],[19.2188,55.4042],[4.66953,30.2042]]
M73 P0 R0
; max_print_temp = 80,237
;TYPE:Custom
M220 S100 ;Reset Feedrate 
M221 S100 ;Reset Flowrate 
 
M140 S80 ;Set final bed temp  
G28 ;Home 
 
G92 E0 ;Reset Extruder 
G1 Z2.0 F3000 ;Move Z Axis up 
M104 S237 ;Set final nozzle temp  
G1 X-2.0 Y20 Z0.28 F5000.0 ;Move to start position 
M190 S80 ;Wait for bed temp to stabilize  
M109 S237 ;Wait for nozzle temp to stabilize  
G1 X-2.0 Y145.0 Z0.28 F1500.0 E15 ;Draw the first line 
M73 P1 R0
G1 X-1.7 Y145.0 Z0.28 F5000.0 ;Move to side a little 
M73 P16 R0
G1 X-1.7 Y20 Z0.28 F1500.0 E30 ;Draw the second line 
G92 E0 ;Reset Extruder 
G1 E-1.0000 F1800 ;Retract a bit 
M73 P31 R0
G1 Z2.0 F3000 ;Move Z Axis up 
G1 E0.0000 F1800
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
SET_PRESSURE_ADVANCE ADVANCE=0.044; Override pressure advance value
G1 E-.8 F1800
G1 Z.2 F27000
M106 S0
;LAYER_CHANGE
;:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=500 ACCEL_TO_DECEL=125
SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=9
; OBJECT_ID: 71
; printing object Part1.STL id:0 copy 0
EXCLUDE_OBJECT_START NAME=Part1.STL_id_0_copy_0
G1 X19.322 Y5.104 Z.4 F27000
G1 Z.2
M73 P33 R0
G1 E.8 F1800
;TYPE:Outer wall
;WIDTH:0.38292
G1 F2578
G1 X48.214 Y5.104 E.77598
G1 X48.282 Y5.143 E.00211
M73 P36 R0
G1 X62.728 Y30.165 E.77598
G1 X62.733 Y30.235 E.00187
M73 P38 R0
G1 X48.282 Y55.265 E.77625
G1 X48.214 Y55.304 E.00211
M73 P40 R0
G1 X19.322 Y55.304 E.77598
G1 X19.254 Y55.265 E.00211
M73 P42 R0
G1 X4.808 Y30.243 E.77598
M73 P43 R0
G1 X4.808 Y30.165 E.00211
M73 P45 R0
G1 X19.254 Y5.143 E.77598
G1 X19.287 Y5.124 E.00104
M73 P47 R0
G1 X19.336 Y5.025
G1 E-.56 F1800
;WIPE_START
G1 F9000
G1 X20.287 Y5.123 E-.228
;WIPE_END
G1 E-.012 F1800
M73 P48 R0
G1 X22.088 Y8.488 Z.4 F27000
G1 X33.787 Y30.347 Z.4
G1 Z.2
M73 P50 R0
G1 E.8 F1800
G1 F2578
G2 X31.886 Y33.968 I8.332 J6.684 E.11052
G2 X32.635 Y40.054 I7.851 J2.123 E.16888
G2 X36.095 Y43.826 I9.844 J-5.558 E.13866
M73 P51 R0
G2 X41.224 Y45.857 I6.866 J-9.846 E.14949
G2 X44.956 Y45.54 I1.158 J-8.51 E.10141
G2 X48.618 Y42.539 I-2.222 J-6.446 E.12988
G2 X49.536 Y40.436 I-9.237 J-5.283 E.06175
; stop printing object Part1.STL id:0 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F9000
G1 X49.199 Y41.377 E-.228
;WIPE_END
G1 E-.012 F1800
EXCLUDE_OBJECT_END NAME=Part1.STL_id_0_copy_0
;TIME_ELAPSED:17.608963

M106 S255
;LAYER_CHANGE
;:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.4
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=5000 ACCEL_TO_DECEL=1250
SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=12
M140 S80 ; set bed temperature
; OBJECT_ID: 71
; printing object Part1.STL id:0 copy 0
EXCLUDE_OBJECT_START NAME=Part1.STL_id_0_copy_0
G1 X19.322 Y5.104 Z.4 F27000
G1 E.8 F1800
SET_VELOCITY_LIMIT ACCEL=2000 ACCEL_TO_DECEL=500 SQUARE_CORNER_VELOCITY=9
G1 F2629
M73 P52 R0
G1 X19.988 Y5.104 E.01789
G1 X47.548 Y5.104 E.74019
G1 X48.214 Y5.104 E.01789
G1 X48.282 Y5.143 E.00211
G1 X48.615 Y5.72 E.01789
G1 X62.395 Y29.588 E.7402
G1 X62.728 Y30.165 E.01789
G1 X62.733 Y30.235 E.00188
G1 X62.401 Y30.811 E.01786
G1 X48.615 Y54.688 E.74049
G1 X48.282 Y55.265 E.01789
G1 X48.214 Y55.304 E.00211
M73 P53 R0
G1 X47.548 Y55.304 E.01789
G1 X19.988 Y55.304 E.74019
G1 X19.322 Y55.304 E.01789
G1 X19.254 Y55.265 E.00211
G1 X18.921 Y54.688 E.01789
G1 X5.141 Y30.82 E.7402
G1 X4.808 Y30.243 E.01789
G1 X4.808 Y30.165 E.00209
G1 X5.141 Y29.588 E.01789
M73 P54 R0
G1 X18.921 Y5.72 E.7402
G1 X19.254 Y5.143 E.01789
G1 X19.287 Y5.124 E.00102
G1 X19.336 Y5.025
M73 P56 R0
G1 E-.56 F1800
;WIPE_START
G1 F11640
G1 X20.287 Y5.123 E-.228
;WIPE_END
G1 E-.012 F1800
SET_VELOCITY_LIMIT ACCEL=5000 ACCEL_TO_DECEL=1250 SQUARE_CORNER_VELOCITY=12
M73 P58 R0
G1 X22.722 Y8.062 Z.6 F27000
G1 X49.536 Y40.436 Z.6
G1 Z.4
G1 E.8 F1800
SET_VELOCITY_LIMIT ACCEL=2000 ACCEL_TO_DECEL=500 SQUARE_CORNER_VELOCITY=9
M73 P60 R0
G1 F2629
G1 X49.195 Y41.386 E.02711
G1 X48.865 Y42.097 E.02105
G1 X48.618 Y42.539 E.0136
M73 P62 R0
G1 X48.21 Y43.151 E.01975
G1 X47.76 Y43.701 E.01909
G1 X47.322 Y44.134 E.01654
G1 X46.798 Y44.579 E.01846
M73 P64 R0
G1 X46.227 Y44.959 E.01842
G1 X45.613 Y45.28 E.01861
G1 X44.956 Y45.54 E.01898
G1 X44.259 Y45.737 E.01945
M73 P66 R0
G1 X43.635 Y45.855 E.01706
M73 P67 R0
G1 X42.863 Y45.928 E.02083
G1 X42.057 Y45.929 E.02165
G1 X41.224 Y45.857 E.02246
G1 X40.37 Y45.709 E.02328
G1 X39.507 Y45.484 E.02395
G1 X38.644 Y45.186 E.02452
G1 X37.796 Y44.817 E.02484
G1 X36.973 Y44.383 E.02499
M73 P68 R0
G1 X36.095 Y43.826 E.02793
G1 X35.364 Y43.278 E.02454
G1 X34.689 Y42.688 E.02408
G1 X34.075 Y42.064 E.02351
G1 X33.527 Y41.414 E.02283
G1 X33.046 Y40.742 E.0222
G1 X32.635 Y40.054 E.02152
G1 X32.292 Y39.354 E.02094
G1 X32.108 Y38.885 E.01353
G1 X31.898 Y38.264 E.01761
G1 X31.731 Y37.557 E.01951
G1 X31.629 Y36.846 E.01929
G1 X31.593 Y36.132 E.0192
M73 P69 R0
G1 X31.623 Y35.415 E.01927
G1 X31.72 Y34.693 E.01957
G1 X31.886 Y33.968 E.01998
G1 X32.122 Y33.238 E.02061
G1 X32.433 Y32.502 E.02146
G1 X32.821 Y31.762 E.02244
G1 X33.291 Y31.016 E.02368
G1 X33.787 Y30.347 E.02237
; stop printing object Part1.STL id:0 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F14040
G1 X33.291 Y31.016 E-.18988
G1 X33.202 Y31.157 E-.03812
;WIPE_END
G1 E-.012 F1800
EXCLUDE_OBJECT_END NAME=Part1.STL_id_0_copy_0
;TIME_ELAPSED:23.208624

;LAYER_CHANGE
;:0.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.6
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
; OBJECT_ID: 71
; printing object Part1.STL id:0 copy 0
EXCLUDE_OBJECT_START NAME=Part1.STL_id_0_copy_0
SET_VELOCITY_LIMIT ACCEL=5000 ACCEL_TO_DECEL=1250 SQUARE_CORNER_VELOCITY=12
G1 X19.322 Y5.104 Z.6 F27000
G1 E.8 F1800
SET_VELOCITY_LIMIT ACCEL=2000 ACCEL_TO_DECEL=500 SQUARE_CORNER_VELOCITY=9
G1 F2608
G1 X19.988 Y5.104 E.01789
M73 P70 R0
G1 X47.548 Y5.104 E.74019
G1 X48.214 Y5.104 E.01789
G1 X48.282 Y5.143 E.00211
G1 X48.615 Y5.72 E.01789
G1 X62.395 Y29.588 E.7402
G1 X62.728 Y30.165 E.01789
G1 X62.733 Y30.235 E.00188
G1 X62.401 Y30.811 E.01786
G1 X48.615 Y54.688 E.74049
G1 X48.282 Y55.265 E.01789
G1 X48.214 Y55.304 E.00211
G1 X47.548 Y55.304 E.01789
G1 X19.988 Y55.304 E.74019
G1 X19.322 Y55.304 E.01789
G1 X19.254 Y55.265 E.00211
G1 X18.921 Y54.688 E.01789
G1 X5.141 Y30.82 E.7402
G1 X4.808 Y30.243 E.01789
G1 X4.808 Y30.165 E.00209
G1 X5.141 Y29.588 E.01789
M73 P71 R0
G1 X18.921 Y5.72 E.7402
G1 X19.254 Y5.143 E.01789
G1 X19.287 Y5.124 E.00102
G1 X19.336 Y5.025
M73 P73 R0
G1 E-.56 F1800
;WIPE_START
G1 F11640
G1 X20.287 Y5.123 E-.228
;WIPE_END
G1 E-.012 F1800
SET_VELOCITY_LIMIT ACCEL=5000 ACCEL_TO_DECEL=1250 SQUARE_CORNER_VELOCITY=12
M73 P75 R0
G1 X22.722 Y8.062 Z.8 F27000
G1 X49.536 Y40.436 Z.8
G1 Z.6
G1 E.8 F1800
SET_VELOCITY_LIMIT ACCEL=2000 ACCEL_TO_DECEL=500 SQUARE_CORNER_VELOCITY=9
M73 P77 R0
G1 F2608
G1 X49.195 Y41.386 E.02711
G1 X48.865 Y42.097 E.02105
G1 X48.618 Y42.539 E.0136
M73 P79 R0
G1 X48.21 Y43.151 E.01975
G1 X47.76 Y43.701 E.01909
G1 X47.322 Y44.134 E.01654
G1 X46.798 Y44.579 E.01846
M73 P81 R0
G1 X46.227 Y44.959 E.01842
G1 X45.613 Y45.28 E.01861
G1 X44.956 Y45.54 E.01898
G1 X44.259 Y45.737 E.01945
M73 P83 R0
G1 X43.635 Y45.855 E.01706
G1 X42.863 Y45.928 E.02083
G1 X42.057 Y45.929 E.02165
M73 P84 R0
G1 X41.224 Y45.857 E.02246
G1 X40.37 Y45.709 E.02328
G1 X39.507 Y45.484 E.02395
G1 X38.644 Y45.186 E.02452
G1 X37.796 Y44.817 E.02484
G1 X36.973 Y44.383 E.02499
M73 P85 R0
G1 X36.095 Y43.826 E.02793
G1 X35.364 Y43.278 E.02454
G1 X34.689 Y42.688 E.02408
G1 X34.075 Y42.064 E.02351
G1 X33.527 Y41.414 E.02283
G1 X33.046 Y40.742 E.0222
G1 X32.635 Y40.054 E.02152
G1 X32.292 Y39.354 E.02094
G1 X32.108 Y38.885 E.01353
G1 X31.898 Y38.264 E.01761
G1 X31.731 Y37.557 E.01951
G1 X31.629 Y36.846 E.01929
G1 X31.593 Y36.132 E.0192
G1 X31.623 Y35.415 E.01927
G1 X31.72 Y34.693 E.01957
M73 P86 R0
G1 X31.886 Y33.968 E.01998
G1 X32.122 Y33.238 E.02061
G1 X32.433 Y32.502 E.02146
G1 X32.821 Y31.762 E.02244
G1 X33.291 Y31.016 E.02368
G1 X33.787 Y30.347 E.02237
; stop printing object Part1.STL id:0 copy 0
G1 E-.56 F1800
;WIPE_START
G1 F14040
G1 X33.291 Y31.016 E-.18988
G1 X33.202 Y31.157 E-.03812
;WIPE_END
G1 E-.012 F1800
EXCLUDE_OBJECT_END NAME=Part1.STL_id_0_copy_0
;TIME_ELAPSED:28.791592

M106 S0
;TYPE:Custom
; filament end gcode 
G91 ;Relative positionning 
G1 E-2 F2700 ;Retract a bit 
G1 E-2 Z0.2 F2400 ;Retract and raise Z 
G1 X3 Y3 F3000 ;Wipe out 
G1 Z5 ;Raise Z more 
G90 ;Absolute positionning 
 
G1 X2 Y218 F3000 ;Present print 
M106 S0 ;Turn-off fan 
M104 S0 ;Turn-off hotend 
M140 S0 ;Turn-off bed 
 
M84 X Y E ;Disable all steppers but Z
M73 P100 R0
;TIME_ELAPSED:32.951935

; EXECUTABLE_BLOCK_END

; filament used [mm] = 46.58
; filament used [cm3] = 0.11
; filament used [g] = 0.14
; filament cost = 0.00
; total filament cost = 0.00
; total layers count = 3
; estimated printing time (normal mode) = 32s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 25%
; acceleration_limit_mess = [[0.3,0.6,150,6000],[0.61,0.9,100,5500],[0.91,1.2,80,5000],[1.21,1.5,60,4500],[1.51,2.0,40,4000]]
; acceleration_limit_mess_enable = 0
; activate_air_filtration = 0
; activate_chamber_layer = 1
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; additional_cooling_fan_speed = 0
; ai_infill = 0
; align_infill_direction_to_model = 0
; alternate_extra_wall = 0
; arc_tolerance = 12
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; belt_Z_offset = 0
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 4
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 0.95
; bridge_no_support = 0
; bridge_speed = 50
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = auto_brim
; brim_width = 0
; chamber_temperature = 35
; change_extrusion_role_gcode = 
; change_filament_gcode = PAUSE
; close_fan_the_first_x_layers = 1
; color_bed_exclude_area = 
; complete_print_exhaust_fan_speed = 80
; cool_cds_fan_start_at_height = 0
; cool_plate_temp = 50
; cool_plate_temp_initial_layer = 50
; cool_special_cds_fan_speed = 0
; cooling_perimeter_transition_distance = 0
; cooling_slowdown_logic = uniform_cooling
; cooling_tube_length = 0
; cooling_tube_retraction = 0
; counterbore_hole_bridging = none
; creality_flush_time = 86
; curr_bed_type = High Temp Plate
; customized_plate_temp = 35
; customized_plate_temp_initial_layer = 35
; default_acceleration = 5000
; default_filament_colour = #56DF3D
; default_filament_profile = "Hyper PLA @Creality Ender-3 V3 KE 0.4 nozzle"
; default_filament_type = PETG
; default_flush_multiplier = 1.3
; default_jerk = 12
; default_print_profile = 0.20mm Standard @Creality Ender-3 V3 KE 0.4 nozzle
; deretraction_speed = 30
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 60
; elefant_foot_compensation = 0.15
; elefant_foot_compensation_layers = 1
; embedding_wall_into_infill = 0
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 1
; enable_filament_ramming = 0
; enable_long_retraction_when_cut = 2
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 1
; enable_prime_tower = 0
; enable_special_area_additional_cooling_fan = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 50
; eng_plate_temp_initial_layer = 50
; ensure_vertical_shell_thickness = ensure_all
; epoxy_resin_plate_temp = 50
; epoxy_resin_plate_temp_initial_layer = 50
; exclude_object = 1
; external_infill_margin = 0
; extra_loading_move = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height_to_lid = 34
; extruder_clearance_height_to_rod = 47
; extruder_clearance_radius = 90
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; fan_cooling_layer_time = 100
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_adhesiveness_category = 100
; filament_colour = #56DF3D
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 30
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n"
; filament_flow_ratio = 0.95
; filament_ids = 01001
; filament_is_support = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 23
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_lift_above = 0
; filament_retract_lift_below = 0
; filament_retract_lift_enforce = All Surfaces
; filament_settings_id = "Hyper PLA @Creality Ender-3 V3 KE 0.4 nozzle - Copy(1)"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = "; filament start gcode\n"
; filament_toolchange_delay = 0
; filament_type = PETG
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Creality
; filename_format = {input_filename_base}_{filament_type[initial_tool]}_{print_time}.gcode
; fill_multiline = 1
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; flush_box_first_clean_length = 90
; flush_box_need_clean_length = 70
; flush_box_need_clean_length_max = 100
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_changed = 0
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_mode = displacement
; fuzzy_skin_noise_type = classic
; fuzzy_skin_octaves = 4
; fuzzy_skin_persistence = 0.5
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_scale = 1
; fuzzy_skin_thickness = 0.3
; gap_fill_target = everywhere
; gap_infill_speed = 100
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 80
; hot_plate_temp_initial_layer = 80
; idle_temperature = 0
; ignore_inner_color = 0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 12
; infill_lock_depth = 1
; infill_overhang_angle = 45
; infill_rotate_step = 0
; infill_shift_step = 0.4
; infill_wall_overlap = 30%
; inherits_group = "0.20mm Standard @Creality Ender-3 V3 KE 0.4 nozzle";"Hyper PLA @Creality Ender-3 V3 KE 0.4 nozzle";
; initial_layer_acceleration = 500
; initial_layer_infill_speed = 105
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 150
; initial_layer_travel_acceleration = 0
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 5000
; inner_wall_jerk = 9
; inner_wall_line_width = 0.45
; inner_wall_speed = 450
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_flow = 1
; internal_bridge_speed = 150%
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.42
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 250
; ironing_angle = -1
; ironing_flow = 15%
; ironing_pattern = zig-zag
; ironing_spacing = 0.1
; ironing_speed = 44
; ironing_support_layer = 0
; ironing_type = no ironing
; is_infill_first = 0
; lateral_lattice_angle_1 = -45
; lateral_lattice_angle_2 = 45
; layer_change_gcode = 
; layer_height = 0.2
; line_width = 0.45
; locked_skeleton_infill_pattern = zig-zag2
; locked_skin_infill_pattern = cross-zag
; long_retractions_when_cut = 0
; machine_LED_light_exist = 0
; machine_end_gcode = G91 ;Relative positionning \nG1 E-2 F2700 ;Retract a bit \nG1 E-2 Z0.2 F2400 ;Retract and raise Z \nG1 X3 Y3 F3000 ;Wipe out \nG1 Z5 ;Raise Z more \nG90 ;Absolute positionning \n \nG1 X2 Y218 F3000 ;Present print \nM106 S0 ;Turn-off fan \nM104 S0 ;Turn-off hotend \nM140 S0 ;Turn-off bed \n \nM84 X Y E ;Disable all steppers but Z
; machine_is_belt = 0
; machine_load_filament_time = 11
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 8000
; machine_max_acceleration_retracting = 5000
; machine_max_acceleration_travel = 8000
; machine_max_acceleration_x = 8000
; machine_max_acceleration_y = 8000
; machine_max_acceleration_z = 500
; machine_max_jerk_e = 5
; machine_max_jerk_x = 12
; machine_max_jerk_y = 12
; machine_max_jerk_z = 0.4
; machine_max_speed_e = 100
; machine_max_speed_x = 500
; machine_max_speed_y = 500
; machine_max_speed_z = 30
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = PAUSE
; machine_platform_motion_enable = 0
; machine_ptc_exist = 0
; machine_start_gcode = M220 S100 ;Reset Feedrate \nM221 S100 ;Reset Flowrate \n \nM140 S[bed_temperature_initial_layer_single] ;Set final bed temp  \nG28 ;Home \n \nG92 E0 ;Reset Extruder \nG1 Z2.0 F3000 ;Move Z Axis up \nM104 S[nozzle_temperature_initial_layer] ;Set final nozzle temp  \nG1 X-2.0 Y20 Z0.28 F5000.0 ;Move to start position \nM190 S[bed_temperature_initial_layer_single] ;Wait for bed temp to stabilize  \nM109 S[nozzle_temperature_initial_layer] ;Wait for nozzle temp to stabilize  \nG1 X-2.0 Y145.0 Z0.28 F1500.0 E15 ;Draw the first line \nG1 X-1.7 Y145.0 Z0.28 F5000.0 ;Move to side a little \nG1 X-1.7 Y20 Z0.28 F1500.0 E30 ;Draw the second line \nG92 E0 ;Reset Extruder \nG1 E-1.0000 F1800 ;Retract a bit \nG1 Z2.0 F3000 ;Move Z Axis up \nG1 E0.0000 F1800
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 1
; material_flow_dependent_temperature = 0
; material_flow_temp_graph = [[2.0,205],[4.0,215],[7.0,220]]
; max_bridge_length = 10
; max_layer_height = 0.36
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_length_factor = 0.5
; min_skirt_length = 0
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 10
; minimum_support_area = 5
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; msao_recovery_enable = 0
; msao_safe_accel = 200
; msao_safe_velocity = 50
; multicolor_method = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_height = 4
; nozzle_hrc = 0
; nozzle_temperature = 237
; nozzle_temperature_initial_layer = 237
; nozzle_temperature_range_high = 240
; nozzle_temperature_range_low = 190
; nozzle_type = brass
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 1
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 2000
; outer_wall_jerk = 9
; outer_wall_line_width = 0.42
; outer_wall_speed = 350
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_optimization = 0
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; overhang_speed_classic = 0
; overhang_totally_speed = 50
; parking_pos_retraction = 0
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 0
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.044
; prime_tower_brim_width = 3
; prime_tower_enable_framework = 0
; prime_tower_enhance_type = chamfer
; prime_tower_position_type = Middle Upper
; prime_tower_rib_wall = 1
; prime_tower_skip_points = 1
; prime_tower_width = 60
; prime_volume = 45
; print_compatible_printers = "Creality Ender-3 V3 KE 0.4 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = PETG
; printable_area = 0x0,220x0,220x220,0x220
; printable_height = 240
; printer_model = Creality Ender-3 V3 KE
; printer_notes = 
; printer_select_mac = 
; printer_settings_id = Creality Ender-3 V3 KE 0.4 nozzle
; printer_structure = i3
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 0
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 70%
; retract_length_toolchange = 1
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.8
; retraction_minimum_travel = 2
; retraction_speed = 30
; role_based_wipe_speed = 1
; rotate_solid_infill_direction = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; skeleton_infill_density = 25%
; skeleton_infill_line_width = 100%
; skin_infill_density = 25%
; skin_infill_depth = 2
; skin_infill_line_width = 100%
; skirt_distance = 2
; skirt_height = 2
; skirt_loops = 0
; skirt_speed = 50
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 5
; slow_down_layers = 0
; slow_down_min_speed = 10
; slowdown_for_curled_perimeters = 0
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; smart_cooling_zones = 0
; smooth_coefficient = 80
; smooth_speed_discontinuity_area = 0
; solid_infill_direction = 45
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = zig-zag
; sparse_infill_speed = 270
; speed_limit_to_height = [[100,150,100,6000],[150,200,80,5500],[200,230,60,5000],[230,250,50,4000]]
; speed_limit_to_height_enable = 0
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; staggered_inner_seams = 1
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_air_filtration = 0
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 2.5
; support_base_pattern_tree = default
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 0
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_min_area = 0.25
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_ironing = 0
; support_ironing_flow = 10%
; support_ironing_pattern = zig-zag
; support_ironing_spacing = 0.2
; support_line_width = 0.42
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 1
; support_object_first_layer_gap = 0.2
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_top_z_distance = 0.2
; support_type = normal(auto)
; support_xy_overrides_z = xy_overrides_z
; symmetric_infill_y_axis = 0
; temperature_vitrification = 60
; template_custom_gcode = 
; textured_plate_temp = 80
; textured_plate_temp_initial_layer = 80
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 96x96/CR_PNG, 300x300/CR_PNG
; thumbnails_format = CR_PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 4
; top_shell_thickness = 0.8
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 5000
; top_surface_jerk = 9
; top_surface_line_width = 0.42
; top_surface_pattern = monotonic
; top_surface_speed = 200
; tpms_end_infill_density = 15%
; tpms_gradual_direction = gradualdir_x
; tpms_start_infill_density = 8%
; travel_acceleration = 5000
; travel_jerk = 12
; travel_short_distance_acceleration = 0
; travel_short_distance_threshold = 1.5
; travel_slope = 3
; travel_speed = 450
; travel_speed_z = 0
; tree_hybrid_cross_height = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 2
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_double_wall = 3
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; tree_support_wall_count_tree = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = arachne
; wall_loops = 3
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 1
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 0.000
; wipe_tower_y = 0.000
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_direction_outwall_speed_continuous = 0
; z_hop = 0.2
; z_hop_types = Slope Lift
; z_offset = 0
; first_layer_bed_temperature = 80
; bed_shape = 0x0,220x0,220x220,0x220
; first_layer_temperature = 237
; first_layer_height = 0.200
; all_surface_with_shell = 1
; should_enable_preview_lod = 1
; CONFIG_BLOCK_END


; gcode_lines = 1058
